### ISSUE TITLE
'wc' not executable on windows

### ISSUE THREAD

**Issue by NicholasSynovic** [SoftwareSystemsLaboratory/ssl-metrics-git-commits-loc#6]
https://superuser.com/questions/959036/what-is-the-windows-equivalent-of-wc-l#959037

**Comment by NicholasSynovic** [comment]
This software is meant to be ran on Linux and Mac.

**Comment by gkthiruvathukal** [comment]
@NicholasSynovic Or Windows Subsystem for Linux. Everything we do works there just fine!
